Controllers/ClasesAdminController.cs
using GestionClasesGimFront.Data.Base;
using GestionClasesGimFront.Data.DTOs;
using GestionClasesGimFront.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;
using System.Net.Http;

namespace GestionClasesGimFront.Controllers
{
    public class ClasesAdminController : Controller
    {
        private readonly IHttpClientFactory _httpClient;

        public ClasesAdminController(IHttpClientFactory httpClient)
        {
            _httpClient = httpClient;
        }
        public IActionResult ClasesAdmin()
        {
            return View();
        }


        public IActionResult GuardarClase(ClaseDto clase)
        {
            var token = HttpContext.Session.GetString("Token");
            var baseApi = new BaseApi(_httpClient);
            var alumnos = baseApi.PostToApi("Clase/Agregar", clase, token);
            return RedirectToAction("Home", "Index");
        }
        public IActionResult alumnosClasePartial([FromQuery]int claseId)
        {
            HttpContext.Session.SetString("idClase", claseId.ToString());
            var token = HttpContext.Session.GetString("Token");
            var baseApi = new BaseApi(_httpClient);

            var response = baseApi.getFromApi($"Clase/ClaseById?claseId={claseId.ToString()}", token).Result;

            if (response is OkObjectResult okResult)
            {
                var json = okResult.Value.ToString();
                var clase = JsonConvert.DeserializeObject<ClaseDto>(json);

                var clasesViewModel = new ClasesViewModel
                {
                    Nombre = clase.Nombre,
                    FechaHorario = clase.FechaHorario,
                    Cupos = clase.Cupos,
                    CapacidadMax = clase.CapacidadMax,
                    imagenUrl = clase.imagenUrl,
                    Activo = clase.Activo

                };

                return View("~/Views/ClasesAdmin/Partial/AlumnosClasePartial.cshtml", clasesViewModel);
            }
            return View("~/Views/ClasesAdmin/Partial/AlumnosClasePartial.cshtml");
        }
    }
}

Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    
    string roleSession = HttpContextAccessor.HttpContext.Session.GetString("Role");

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionClasesGimFront</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestionClasesGimFront.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Utils/Utils.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://kit.fontawesome.com/f8fcaa487b.js" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    @if (int.Parse(roleSession) == 1)
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GalatasGym</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ClasesAdmin" asp-action="ClasesAdmin">Clases</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Usuarios">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Alumnos" asp-action="Alumnos">Alumnos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="CerrarSesion">CerrarSesion</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }
    else
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestionClasesGimFront</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clases" asp-action="Clases">Clases</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Perfil" asp-action="Perfil">Perfil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="CerrarSesion">CerrarSesion</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GaltasGym
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>